config/routes.rb
require "constraints/subdomain_required"

Twist::Application.routes.draw do
  devise_for :users

  constraints(SubdomainRequired) do
    scope module: "accounts" do
      root to: "books#index", as: :account_root

      resources :invitations, only: [:new, :create] do
        member do
          get :accept
          patch :accepted
        end
      end

      resources :users, only: [:index, :destroy]

      notes_routes = lambda do
        collection do
          get :completed
        end

        member do
          put :accept
          put :reject
          put :reopen
        end

        resources :comments
      end

      resources :books do
        member do
          post :receive
        end

        resources :chapters do
          resources :elements do
            resources :notes
          end

          resources :notes, &notes_routes
        end

        resources :notes, &notes_routes
      end
    end
  end

  root to: "home#index"
  get "/accounts/new", to: "accounts#new", as: :new_account
  post "/accounts", to: "accounts#create", as: :accounts

  get "signed_out", to: "users#signed_out"
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :element, counter_cache: true
  has_many :comments

  accepts_nested_attributes_for :comments

  delegate :chapter, to: :element

  belongs_to :user, optional: true

  def to_param
    number.to_s
  end

  def accept!
    self.state = "accepted"
    self.save!
  end

  def reject!
    self.state = "rejected"
    self.save!
  end

  def reopen!
    self.state = "reopened"
    self.save!
  end

  def completed?
    ["accepted", "rejected"].include?(state)
  end
end

app/controllers/accounts/notes_controller.rb
module Accounts
  class NotesController < Accounts::BaseController
    before_action :find_book_and_chapter
    before_action :find_note, only: [:show, :complete, :reopen]
    before_action :find_notes, only: [:index, :completed]

    def index
      @notes = @notes.where(state: ["new", "reopened"])
    end

    def show
      @chapter = @note.chapter
      @comment = @note.comments.build
      @comments = @note.comments - [@comment]
    end

    def new
      @note = Note.new
      @note.comments.build
      @element = Element.find_by(nickname: params[:element_id])
      @notes = @element.notes
    end

    def create
      element = @chapter.elements.find_by(nickname: params[:element_id])
      number = @book.notes_count + 1
      new_note_params = note_params.merge(
        number: number,
        user: current_user
      )

      note = element.notes.build(new_note_params)
      note.comments.first.user = current_user

      if note.save
        # Increment notes count for the book
        @book.notes_count += 1
        @book.save
        # create.js.erb
      else
        # TODO: validation error if note text is blank
      end
    end

    def completed
      @notes = @notes.where(state: ["accepted", "rejected"])
      @title = "Completed notes"
      render :index
    end

    private

      def find_notes
        if @chapter
          @notes = @chapter.notes
        else
          @notes = @book.notes
        end
      end

      def find_note
        @note = @book.notes.find_by(number: params[:id])
      end

      def find_book_and_chapter
        @book = Book.find_by_permalink(params[:book_id])
        @chapter = @book.chapters.find_by(permalink: params[:chapter_id]) if params[:chapter_id]
      end

      def note_params
        params.require(:note).permit(comments_attributes: [:text])
      end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def avatar(user)
    # Do not connect out to gravatar in tests
    if user && !Rails.env.test?
      image_tag "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=140"
    else
      image_tag "missing.png"
    end
  end

  def state(note)
    attributes = case note.state.titleize
                  when "Accepted"
                    { :class => "state-accepted" }
                  when "Rejected"
                    { :class => "state-rejected" }
                  when "New", "Reopened"
                    { :class => "state-new" }
                  end
    content_tag(:span, attributes) { note.state.titleize }
  end
end

app/views/notes/_form.js.erb
<%= form_with(model: [@book, @chapter, :element, @note]) do |f| %>
  <%= f.fields_for :comments do |comment| %>
    <div class='form-group'>
      <%= comment.label :text, "Leave a note (Markdown enabled)" %>
      <%= comment.text_area :text, class: "form-control" %>
    </div>
  <% end %>

  <p>
    <%= f.submit "Leave Note", class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/notes/new.js.erb
<% partial = render('notes/form') %>
container = $('#notes_container_<%= params[:element_id] %>');
container.toggle();
container.html(<%= raw(partial.inspect) %>);
<% if !@notes.empty? %>
  container.append("<h4>Previous Notes</h4>");
  container.append(<%= raw(render(@notes).inspect) %>);
  container.append("<hr>")
<% end %>

app/views/notes/show.html.erb
<div class='row'>
  <div class='content col-md-8 offset-md-2 note'>
    <% @full_page = true %>
    <% chapter = @note.chapter %>
    <% book = chapter.book %>
    <h2>
      <%= link_to book.title, book %> -
      <%= link_to "#{chapter.position}: #{chapter.title}", [book, chapter] %></h2>
    <h3>Note #<%= @note.number %> - <%= state(@note) %></h3>
    <%= render_element(@note.element, show_notes: false) %>
    <strong><%= link_to "View this element within chapter", book_chapter_path(book, chapter, :anchor => @note.element.nickname) %></strong>

    <div id='comments'>
      <%= render @comments.select(&:persisted?) %>
    </div>

    <%= render "comments/form" %>
  </div>
</div>