config/routes.rb
require "constraints/subdomain_required"

Twist::Application.routes.draw do
  devise_for :users

  constraints(SubdomainRequired) do
    scope module: "accounts" do
      root to: "books#index", as: :account_root

      resources :invitations, only: [:new, :create] do
        member do
          get :accept
          patch :accepted
        end
      end

      resources :users, only: [:index, :destroy]

      notes_routes = lambda do
        collection do
          get :completed
        end

        member do
          put :accept
          put :reject
          put :reopen
        end

        resources :comments
      end

      resources :books do
        member do
          post :receive
        end

        resources :chapters do
          resources :elements do
            resources :notes
          end

          resources :notes, &notes_routes
        end

        resources :notes, &notes_routes
      end
    end
  end

  root to: "home#index"
  get "/accounts/new", to: "accounts#new", as: :new_account
  post "/accounts", to: "accounts#create", as: :accounts

  get "signed_out", to: "users#signed_out"
end

app/views/notifier/comment.html.erb
<strong>Hello!</strong>

<p><%= @comment.user.email %> just left a comment on <%= link_to "Note ##{@note.number}", book_note_url(@book, @note, subdomain: @account.subdomain) %> for <%= @book.title %>:</p>

<%= markdown(@comment.text) %> 

<p>Love,<br>
The Twist Bot.</p>

app/views/notifier/new_note.html.erb
<strong>Hello!</strong>

<p>
  <%= @note.user.email %> just created a note: <%= link_to "Note ##{@note.number}", book_note_url(@book, @note, subdomain: @account.subdomain) %> for <%= @book.title %>:
</p>

<%= markdown(@comment.text) %>



<p>Love,<br>
The Twist Bot.</p>