config/routes.rb
require "constraints/subdomain_required"

Twist::Application.routes.draw do
  devise_for :users

  constraints(SubdomainRequired) do
    scope module: "accounts" do
      root to: "books#index", as: :account_root

      resources :invitations, only: [:new, :create] do
        member do
          get :accept
          patch :accepted
        end
      end

      resources :users, only: [:index, :destroy]

      notes_routes = lambda do
        collection do
          get :completed
        end

        member do
          put :accept
          put :reject
          put :reopen
        end

        resources :comments
      end

      resources :books do
        member do
          post :receive
        end

        resources :chapters do
          resources :elements do
            resources :notes
          end

          resources :notes, &notes_routes
        end

        resources :notes, &notes_routes
      end
    end
  end

  root to: "home#index"
  get "/accounts/new", to: "accounts#new", as: :new_account
  post "/accounts", to: "accounts#create", as: :accounts

  get "signed_out", to: "users#signed_out"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class='content col-md-8'>
  <% if user_signed_in? %>
    <h2>Pick an account</h2>
    <ul class="accounts">
      <% current_user.all_accounts.each do |account| %>
        <li>
          <%= link_to root_url(subdomain: account.subdomain) do %>
            <%= account.name %> (<%= account.subdomain %>)
          <% end %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <%= link_to "Create a new account", new_account_path %>
  <% end %>
</div>